import QtQuick 2.0
import Sailfish.Silica 1.0
import "../components"

SilicaFlickable {
    id: panel

    property var carousel

    flickableDirection: Flickable.VerticalFlick
    contentHeight: column.height + Theme.paddingLarge * 3

    PanelPulley { carousel: panel.carousel }

    Column {
        id: column
        width: panel.width
        spacing: Theme.paddingMedium

        PageHeader {
            title: qsTr("Payment card")
            description: qsTr("EMV contactless")
        }

        Column {
            width: column.width
            spacing: Theme.paddingSmall
            visible: Nfc.detailFrequency.length > 0

            SectionHeader { text: qsTr("Frequency") }

            FrequencyBand {
                x: Theme.horizontalPageMargin
                width: parent.width - 2 * Theme.horizontalPageMargin
                active: Nfc.detailFrequency
            }
        }

        Repeater {
            model: Nfc.detailKind === "payment" ? Nfc.detailFields : []
            DataField {
                x: Theme.horizontalPageMargin
                width: column.width - 2 * Theme.horizontalPageMargin
                label: modelData.label
                value: modelData.value
                // Same rule as everywhere else. Forcing this to false here
                // made the panel disagree with the Read panel about the very
                // same field, which is worse than the point it was making.
                emittable: modelData.emittable
                mono: modelData.mono
            }
        }

        Label {
            visible: Nfc.detailKind !== "payment"
            x: Theme.horizontalPageMargin
            width: parent.width - 2 * Theme.horizontalPageMargin
            wrapMode: Text.Wrap
            text: qsTr("No payment card in the current read.")
            color: Theme.secondaryColor
            font.pixelSize: Theme.fontSizeSmall
        }

        InfoBlock {
            x: Theme.horizontalPageMargin
            width: parent.width - 2 * Theme.horizontalPageMargin
            title: qsTr("What is readable")
            works: [
                qsTr("The payment system environment (PPSE) and the list of applications the card offers"),
                qsTr("Application labels and priorities, and on many cards the primary account number and expiry date"),
                qsTr("On some cards, the last transactions")
            ]
            blocked: [
                qsTr("Anything secret. The keys never leave the card's secure element.")
            ]
        }

        InfoBlock {
            x: Theme.horizontalPageMargin
            width: parent.width - 2 * Theme.horizontalPageMargin
            title: qsTr("Why paying with this is impossible")
            works: []
            blocked: [
                qsTr("Nothing is copied when a phone pays. Google Pay and Apple Pay are provisioned with a device specific token by the card scheme after the bank authenticated you - the real card number is never on the phone."),
                qsTr("A read cannot be replayed. Every transaction needs a fresh cryptogram that the card computes with a key it will not disclose, over an unpredictable number the terminal supplies."),
                qsTr("Getting a token instead requires a certified secure element and attestation to the scheme. SailfishOS has neither, and no bank provisions to it."),
                qsTr("Protocol-wise this app could register the Visa AID and answer the terminal. It would get exactly as far as the request for a valid cryptogram - and building a working one would be card fraud, not a hobby project.")
            ]
            footnote: qsTr("Green may still appear above: a 4 byte NFCID1 can be presented by this phone. But that identifier is randomly generated by the card for each session anyway - it is not the card, and it buys you nothing at a terminal.")
        }

        Glossary {
            x: Theme.horizontalPageMargin
            width: column.width - 2 * Theme.horizontalPageMargin
        }
    }

    VerticalScrollDecorator { }
}
